//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konto ähnelt.
        /// </summary>
        internal static string CsvPairs_Account {
            get {
                return ResourceManager.GetString("CsvPairs_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jahrestag ähnelt.
        /// </summary>
        internal static string CsvPairs_Anniversary {
            get {
                return ResourceManager.GetString("CsvPairs_Anniversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assistent(in) ähnelt.
        /// </summary>
        internal static string CsvPairs_AssistantsName {
            get {
                return ResourceManager.GetString("CsvPairs_AssistantsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefon Assistent ähnelt.
        /// </summary>
        internal static string CsvPairs_AssistantsPhone {
            get {
                return ResourceManager.GetString("CsvPairs_AssistantsPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abrechnungsinformation ähnelt.
        /// </summary>
        internal static string CsvPairs_BillingInformation {
            get {
                return ResourceManager.GetString("CsvPairs_BillingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geburtstag ähnelt.
        /// </summary>
        internal static string CsvPairs_Birthday {
            get {
                return ResourceManager.GetString("CsvPairs_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Büro ähnelt.
        /// </summary>
        internal static string CsvPairs_BusinessAddress {
            get {
                return ResourceManager.GetString("CsvPairs_BusinessAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Postfach geschäftlich ähnelt.
        /// </summary>
        internal static string CsvPairs_BusinessAddressPOBox {
            get {
                return ResourceManager.GetString("CsvPairs_BusinessAddressPOBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ort geschäftlich ähnelt.
        /// </summary>
        internal static string CsvPairs_BusinessCity {
            get {
                return ResourceManager.GetString("CsvPairs_BusinessCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Land/Region geschäftlich ähnelt.
        /// </summary>
        internal static string CsvPairs_BusinessCountry {
            get {
                return ResourceManager.GetString("CsvPairs_BusinessCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fax geschäftlich ähnelt.
        /// </summary>
        internal static string CsvPairs_BusinessFax {
            get {
                return ResourceManager.GetString("CsvPairs_BusinessFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefon geschäftlich ähnelt.
        /// </summary>
        internal static string CsvPairs_BusinessPhone {
            get {
                return ResourceManager.GetString("CsvPairs_BusinessPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefon geschäftlich 2 ähnelt.
        /// </summary>
        internal static string CsvPairs_BusinessPhone2 {
            get {
                return ResourceManager.GetString("CsvPairs_BusinessPhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Postleitzahl geschäftlich ähnelt.
        /// </summary>
        internal static string CsvPairs_BusinessPostalCode {
            get {
                return ResourceManager.GetString("CsvPairs_BusinessPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Region geschäftlich ähnelt.
        /// </summary>
        internal static string CsvPairs_BusinessState {
            get {
                return ResourceManager.GetString("CsvPairs_BusinessState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Straße geschäftlich ähnelt.
        /// </summary>
        internal static string CsvPairs_BusinessStreet {
            get {
                return ResourceManager.GetString("CsvPairs_BusinessStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Straße geschäftlich 2 ähnelt.
        /// </summary>
        internal static string CsvPairs_BusinessStreet2 {
            get {
                return ResourceManager.GetString("CsvPairs_BusinessStreet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Straße geschäftlich 3 ähnelt.
        /// </summary>
        internal static string CsvPairs_BusinessStreet3 {
            get {
                return ResourceManager.GetString("CsvPairs_BusinessStreet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rückmeldung ähnelt.
        /// </summary>
        internal static string CsvPairs_Callback {
            get {
                return ResourceManager.GetString("CsvPairs_Callback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Autotelefon ähnelt.
        /// </summary>
        internal static string CsvPairs_CarPhone {
            get {
                return ResourceManager.GetString("CsvPairs_CarPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorien ähnelt.
        /// </summary>
        internal static string CsvPairs_Categories {
            get {
                return ResourceManager.GetString("CsvPairs_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kinder ähnelt.
        /// </summary>
        internal static string CsvPairs_Children {
            get {
                return ResourceManager.GetString("CsvPairs_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Firma ähnelt.
        /// </summary>
        internal static string CsvPairs_Company {
            get {
                return ResourceManager.GetString("CsvPairs_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefon Firma ähnelt.
        /// </summary>
        internal static string CsvPairs_CompanyMainPhone {
            get {
                return ResourceManager.GetString("CsvPairs_CompanyMainPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abteilung ähnelt.
        /// </summary>
        internal static string CsvPairs_Department {
            get {
                return ResourceManager.GetString("CsvPairs_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verzeichnisserver ähnelt.
        /// </summary>
        internal static string CsvPairs_DirectoryServer {
            get {
                return ResourceManager.GetString("CsvPairs_DirectoryServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail 2: Adresse ähnelt.
        /// </summary>
        internal static string CsvPairs_Email2Address {
            get {
                return ResourceManager.GetString("CsvPairs_Email2Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail 3: Adresse ähnelt.
        /// </summary>
        internal static string CsvPairs_Email3Address {
            get {
                return ResourceManager.GetString("CsvPairs_Email3Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail-Adresse ähnelt.
        /// </summary>
        internal static string CsvPairs_EmailAddress {
            get {
                return ResourceManager.GetString("CsvPairs_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorname ähnelt.
        /// </summary>
        internal static string CsvPairs_FirstName {
            get {
                return ResourceManager.GetString("CsvPairs_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geschlecht ähnelt.
        /// </summary>
        internal static string CsvPairs_Gender {
            get {
                return ResourceManager.GetString("CsvPairs_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hobby ähnelt.
        /// </summary>
        internal static string CsvPairs_Hobby {
            get {
                return ResourceManager.GetString("CsvPairs_Hobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ort ähnelt.
        /// </summary>
        internal static string CsvPairs_HomeAddress {
            get {
                return ResourceManager.GetString("CsvPairs_HomeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Postfach privat ähnelt.
        /// </summary>
        internal static string CsvPairs_HomeAddressPOBox {
            get {
                return ResourceManager.GetString("CsvPairs_HomeAddressPOBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ort privat ähnelt.
        /// </summary>
        internal static string CsvPairs_HomeCity {
            get {
                return ResourceManager.GetString("CsvPairs_HomeCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Land/Region privat ähnelt.
        /// </summary>
        internal static string CsvPairs_HomeCountry {
            get {
                return ResourceManager.GetString("CsvPairs_HomeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fax privat ähnelt.
        /// </summary>
        internal static string CsvPairs_HomeFax {
            get {
                return ResourceManager.GetString("CsvPairs_HomeFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefon (privat) ähnelt.
        /// </summary>
        internal static string CsvPairs_HomePhone {
            get {
                return ResourceManager.GetString("CsvPairs_HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefon (privat 2) ähnelt.
        /// </summary>
        internal static string CsvPairs_HomePhone2 {
            get {
                return ResourceManager.GetString("CsvPairs_HomePhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Postleitzahl privat ähnelt.
        /// </summary>
        internal static string CsvPairs_HomePostalCode {
            get {
                return ResourceManager.GetString("CsvPairs_HomePostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bundesland/Kanton privat ähnelt.
        /// </summary>
        internal static string CsvPairs_HomeState {
            get {
                return ResourceManager.GetString("CsvPairs_HomeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Straße privat ähnelt.
        /// </summary>
        internal static string CsvPairs_HomeStreet {
            get {
                return ResourceManager.GetString("CsvPairs_HomeStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Straße privat 2 ähnelt.
        /// </summary>
        internal static string CsvPairs_HomeStreet2 {
            get {
                return ResourceManager.GetString("CsvPairs_HomeStreet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Straße privat 3 ähnelt.
        /// </summary>
        internal static string CsvPairs_HomeStreet3 {
            get {
                return ResourceManager.GetString("CsvPairs_HomeStreet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initialen ähnelt.
        /// </summary>
        internal static string CsvPairs_Initials {
            get {
                return ResourceManager.GetString("CsvPairs_Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internet Frei/Gebucht ähnelt.
        /// </summary>
        internal static string CsvPairs_InternetFreeBusy {
            get {
                return ResourceManager.GetString("CsvPairs_InternetFreeBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ISDN ähnelt.
        /// </summary>
        internal static string CsvPairs_ISDN {
            get {
                return ResourceManager.GetString("CsvPairs_ISDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position ähnelt.
        /// </summary>
        internal static string CsvPairs_JobTitle {
            get {
                return ResourceManager.GetString("CsvPairs_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stichwörter ähnelt.
        /// </summary>
        internal static string CsvPairs_Keywords {
            get {
                return ResourceManager.GetString("CsvPairs_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        internal static string CsvPairs_Language {
            get {
                return ResourceManager.GetString("CsvPairs_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nachname ähnelt.
        /// </summary>
        internal static string CsvPairs_LastName {
            get {
                return ResourceManager.GetString("CsvPairs_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location ähnelt.
        /// </summary>
        internal static string CsvPairs_Location {
            get {
                return ResourceManager.GetString("CsvPairs_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name des/r Vorgesetzten ähnelt.
        /// </summary>
        internal static string CsvPairs_ManagersName {
            get {
                return ResourceManager.GetString("CsvPairs_ManagersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weitere Vornamen ähnelt.
        /// </summary>
        internal static string CsvPairs_MiddleName {
            get {
                return ResourceManager.GetString("CsvPairs_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reisekilometer ähnelt.
        /// </summary>
        internal static string CsvPairs_Mileage {
            get {
                return ResourceManager.GetString("CsvPairs_Mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mobiltelefon ähnelt.
        /// </summary>
        internal static string CsvPairs_MobilePhone {
            get {
                return ResourceManager.GetString("CsvPairs_MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mobiltelefon 2 ähnelt.
        /// </summary>
        internal static string CsvPairs_MobilePhone2 {
            get {
                return ResourceManager.GetString("CsvPairs_MobilePhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notizen ähnelt.
        /// </summary>
        internal static string CsvPairs_Notes {
            get {
                return ResourceManager.GetString("CsvPairs_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adresse geschäftlich ähnelt.
        /// </summary>
        internal static string CsvPairs_OfficeLocation {
            get {
                return ResourceManager.GetString("CsvPairs_OfficeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Organisationsnr. ähnelt.
        /// </summary>
        internal static string CsvPairs_OrganizationalIDNumber {
            get {
                return ResourceManager.GetString("CsvPairs_OrganizationalIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weitere Adresse ähnelt.
        /// </summary>
        internal static string CsvPairs_OtherAddress {
            get {
                return ResourceManager.GetString("CsvPairs_OtherAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiteres Postfach ähnelt.
        /// </summary>
        internal static string CsvPairs_OtherAddressPOBox {
            get {
                return ResourceManager.GetString("CsvPairs_OtherAddressPOBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiterer Ort ähnelt.
        /// </summary>
        internal static string CsvPairs_OtherCity {
            get {
                return ResourceManager.GetString("CsvPairs_OtherCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiteres/e Land/Region ähnelt.
        /// </summary>
        internal static string CsvPairs_OtherCountry {
            get {
                return ResourceManager.GetString("CsvPairs_OtherCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiteres Fax ähnelt.
        /// </summary>
        internal static string CsvPairs_OtherFax {
            get {
                return ResourceManager.GetString("CsvPairs_OtherFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiteres Telefon ähnelt.
        /// </summary>
        internal static string CsvPairs_OtherPhone {
            get {
                return ResourceManager.GetString("CsvPairs_OtherPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weitere Postleitzahl ähnelt.
        /// </summary>
        internal static string CsvPairs_OtherPostalCode {
            get {
                return ResourceManager.GetString("CsvPairs_OtherPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiteres/r Bundesland/Kanton ähnelt.
        /// </summary>
        internal static string CsvPairs_OtherState {
            get {
                return ResourceManager.GetString("CsvPairs_OtherState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weitere Straße ähnelt.
        /// </summary>
        internal static string CsvPairs_OtherStreet {
            get {
                return ResourceManager.GetString("CsvPairs_OtherStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weitere Straße 2 ähnelt.
        /// </summary>
        internal static string CsvPairs_OtherStreet2 {
            get {
                return ResourceManager.GetString("CsvPairs_OtherStreet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weitere Straße 3 ähnelt.
        /// </summary>
        internal static string CsvPairs_OtherStreet3 {
            get {
                return ResourceManager.GetString("CsvPairs_OtherStreet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pager ähnelt.
        /// </summary>
        internal static string CsvPairs_Pager {
            get {
                return ResourceManager.GetString("CsvPairs_Pager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Haupttelefon ähnelt.
        /// </summary>
        internal static string CsvPairs_PrimaryPhone {
            get {
                return ResourceManager.GetString("CsvPairs_PrimaryPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Priorität ähnelt.
        /// </summary>
        internal static string CsvPairs_Priority {
            get {
                return ResourceManager.GetString("CsvPairs_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privat ähnelt.
        /// </summary>
        internal static string CsvPairs_Private {
            get {
                return ResourceManager.GetString("CsvPairs_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beruf ähnelt.
        /// </summary>
        internal static string CsvPairs_Profession {
            get {
                return ResourceManager.GetString("CsvPairs_Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Funkruf ähnelt.
        /// </summary>
        internal static string CsvPairs_RadioPhone {
            get {
                return ResourceManager.GetString("CsvPairs_RadioPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empfohlen von ähnelt.
        /// </summary>
        internal static string CsvPairs_ReferredBy {
            get {
                return ResourceManager.GetString("CsvPairs_ReferredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vertraulichkeit ähnelt.
        /// </summary>
        internal static string CsvPairs_Sensitivity {
            get {
                return ResourceManager.GetString("CsvPairs_Sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Partner ähnelt.
        /// </summary>
        internal static string CsvPairs_Spouse {
            get {
                return ResourceManager.GetString("CsvPairs_Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suffix ähnelt.
        /// </summary>
        internal static string CsvPairs_Suffix {
            get {
                return ResourceManager.GetString("CsvPairs_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telex ähnelt.
        /// </summary>
        internal static string CsvPairs_Telex {
            get {
                return ResourceManager.GetString("CsvPairs_Telex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anrede ähnelt.
        /// </summary>
        internal static string CsvPairs_Title {
            get {
                return ResourceManager.GetString("CsvPairs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefon für Hörbehinderte ähnelt.
        /// </summary>
        internal static string CsvPairs_TTY_TDDPhone {
            get {
                return ResourceManager.GetString("CsvPairs_TTY_TDDPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzer 1 ähnelt.
        /// </summary>
        internal static string CsvPairs_User1 {
            get {
                return ResourceManager.GetString("CsvPairs_User1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzer 2 ähnelt.
        /// </summary>
        internal static string CsvPairs_User2 {
            get {
                return ResourceManager.GetString("CsvPairs_User2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzer 3 ähnelt.
        /// </summary>
        internal static string CsvPairs_User3 {
            get {
                return ResourceManager.GetString("CsvPairs_User3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzer 4 ähnelt.
        /// </summary>
        internal static string CsvPairs_User4 {
            get {
                return ResourceManager.GetString("CsvPairs_User4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Webseite ähnelt.
        /// </summary>
        internal static string CsvPairs_WebPage {
            get {
                return ResourceManager.GetString("CsvPairs_WebPage", resourceCulture);
            }
        }
    }
}
