using System;
using System.Collections.Generic;

namespace Google2Outlook
{
    public class CsvPairs
    {
        public static Dictionary<String, String> Fields = new Dictionary<string, string>
        {
            {"First Name", "Vorname"},
            {"Middle Name", "Weitere Vornamen"},
            {"Last Name", "Nachname"},
            {"Title", "Anrede"},
            {"Suffix", "Suffix"},
            {"Initials", "Initialen"},
            {"Web Page", "Webseite"},
            {"Gender", "Geschlecht"},
            {"Birthday", "Geburtstag"},
            {"Anniversary", "Jahrestag"},
            {"Location", "Location"}, //Kein Feld in Oulook vorhanden
            {"Language", "Sprache"},
            {"Internet Free Busy", "Internet Frei/Gebucht"},
            {"Notes", "Notizen"},
            {"E-mail Address", "E-Mail-Adresse"},
            {"E-mail 2 Address", "E-Mail 2: Adresse"},
            {"E-mail 3 Address", "E-Mail 3: Adresse"},
            {"Primary Phone", "Haupttelefon"},
            {"Home Phone", "Telefon (privat)"},
            {"Home Phone 2", "Telefon (privat 2)"},
            {"Mobile Phone", "Mobiltelefon"},
            {"Mobile Phone 2", "Mobiltelefon 2"},
            {"Pager", "Pager"},
            {"Home Fax", "Fax privat"},
            {"Home Address", "Ort"},
            {"Home Street", "Straße privat"},
            {"Home Street 2", "Straße privat 2"},
            {"Home Street 3", "Straße privat 3"},
            {"Home Address PO Box", "Postfach privat"},
            {"Home City", "Ort privat"},
            {"Home State", "Bundesland/Kanton privat"},
            {"Home Postal Code", "Postleitzahl privat"},
            {"Home Country", "Land/Region privat"},
            {"Spouse", "Partner"},
            {"Children", "Kinder"},
            {"Manager's Name", "Name des/r Vorgesetzten"},
            {"Assistant's Name", "Assistent(in)"},
            {"Referred By", "Empfohlen von"},
            {"Company Main Phone", "Telefon Firma"},
            {"Business Phone", "Telefon geschäftlich"},
            {"Business Phone 2", "Telefon geschäftlich 2"},
            {"Business Fax", "Fax geschäftlich"},
            {"Assistant's Phone", "Telefon Assistent"},
            {"Company", "Firma"},
            {"Job Title", "Position"},
            {"Department", "Abteilung"},
            {"Office Location", "Adresse geschäftlich"},
            {"Organizational ID Number", "Organisationsnr."},
            {"Profession", "Beruf"},
            {"Account", "Konto"},
            {"Business Address", "Büro"},
            {"Business Street", "Straße geschäftlich"},
            {"Business Street 2", "Straße geschäftlich 2"},
            {"Business Street 3", "Straße geschäftlich 3"},
            {"Business Address PO Box", "Postfach geschäftlich"},
            {"Business City", "Ort geschäftlich"},
            {"Business State", "Region geschäftlich"},
            {"Business Postal Code", "Postleitzahl geschäftlich"},
            {"Business Country", "Land/Region geschäftlich"},
            {"Other Phone", "Weiteres Telefon"},
            {"Other Fax", "Weiteres Fax"},
            {"Other Address", "Weitere Adresse"},
            {"Other Street", "Weitere Straße"},
            {"Other Street 2", "Weitere Straße 2"},
            {"Other Street 3", "Weitere Straße 3"},
            {"Other Address PO Box", "Weiteres Postfach"},
            {"Other City", "Weiterer Ort"},
            {"Other State", "Weiteres/r Bundesland/Kanton"},
            {"Other Postal Code", "Weitere Postleitzahl"},
            {"Other Country", "Weiteres/e Land/Region"},
            {"Callback", "Rückmeldung"},
            {"Car Phone", "Autotelefon"},
            {"Radio Phone", "Funkruf"},
            {"ISDN", "ISDN"},
            {"TTY/TDD Phone", "Telefon für Hörbehinderte"},
            {"Telex", "Telex"},
            {"User 1", "Benutzer 1"},
            {"User 2", "Benutzer 2"},
            {"User 3", "Benutzer 3"},
            {"User 4", "Benutzer 4"},
            {"Keywords", "Stichwörter"},
            {"Mileage", "Reisekilometer"},
            {"Hobby", "Hobby"},
            {"Billing Information", "Abrechnungsinformation"},
            {"Directory Server", "Verzeichnisserver"},
            {"Sensitivity", "Vertraulichkeit"},
            {"Priority", "Priorität"},
            {"Private", "Privat"},
            {"Categories", "Kategorien"}
        };
    }
}